services:
  - type: web
    name: lucky-draw-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: NODE_ENV=production node server/index-prod-api-only.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: lucky-draw-db
          property: connectionString

databases:
  - name: lucky-draw-db
    databaseName: luckydb
    user: luckyuser
    plan: free
    postgresMajorVersion: 15
